
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVC = 4;
  public static final int LLAVA = 3;
  public static final int ALFAMAYUS = 18;
  public static final int GUION = 9;
  public static final int CBOOL = 17;
  public static final int ONDGUION = 10;
  public static final int ALFAMINUS = 19;
  public static final int CDOBLE = 11;
  public static final int CESPECIAL = 21;
  public static final int COMA = 5;
  public static final int PP = 7;
  public static final int NUMEROS = 20;
  public static final int IDTEXT = 22;
  public static final int MAYOR = 8;
  public static final int EOF = 0;
  public static final int DCONJ = 2;
  public static final int CKLEENE = 14;
  public static final int DISYUNCION = 16;
  public static final int error = 1;
  public static final int SPORCENT = 12;
  public static final int PCOMA = 6;
  public static final int CONCATENAR = 15;
  public static final int CPOSITIVA = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DCONJ",
  "LLAVA",
  "LLAVC",
  "COMA",
  "PCOMA",
  "PP",
  "MAYOR",
  "GUION",
  "ONDGUION",
  "CDOBLE",
  "SPORCENT",
  "CPOSITIVA",
  "CKLEENE",
  "CONCATENAR",
  "DISYUNCION",
  "CBOOL",
  "ALFAMAYUS",
  "ALFAMINUS",
  "NUMEROS",
  "CESPECIAL",
  "IDTEXT"
  };
}

